name: iOS 构建

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Java 环境
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 设置 Flutter 环境
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
      
      - name: 获取依赖
        run: flutter pub get
        
      - name: 构建iOS应用
        run: |
          cd ios
          rm -rf Pods
          rm -rf Podfile.lock
          pod repo update
          pod install --repo-update
          cd ..
          flutter build ios --release --no-codesign
      
      - name: 创建IPA文件
        run: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r app.ipa Payload
          ls -la
          echo "生成的IPA文件:"
          ls -la app.ipa || echo "IPA文件未生成"
          cd ../../..
          
      - name: 上传IPA文件
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: build/ios/iphoneos/app.ipa
          retention-days: 7
          
      - name: 上传未签名构建产物
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos
          retention-days: 7 